#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
patch_tool.py — sirzipp .so binary ထဲက Admin ID နဲ့ Bot Token ကို ပြောင်းပေးတဲ့ tool

═════════════════════════════════════════════════════════════
ADMIN ID (တိုက်ရိုက် binary patch — byte level)
═════════════════════════════════════════════════════════════
Binary ထဲက ADMIN_IDS = [8556036826] က file offset 0x9b32 မှာ x86-64
instruction `movabs $ID, %r12` ရဲ့ 8-byte immediate operand အဖြစ် သိမ
်းထာားတာမို့ byte length မပြောင်းဘဲ တိတိကျပေ လိုကျစွာ ပြောင်းလို့ရတာပါ။

    python3 patch_tool.py admin 1767590675
    python3 patch_tool.py admin 1767590675 --file /path/to/sirzipp.so
    python3 patch_tool.py admin --check-only
    python3 patch_tool.py admin --restore          # မူရင်း 8556036826 ပြန်ထားမယ်

═════════════════════════════════════════════════════════════
BOT TOKEN (runtime override loader ဖန်တီးခြင်း)
═════════════════════════════════════════════════════════════
Bot Token က binary ထဲမှာ compress လုပ်ထားတာမို့ binary patch လုပ်လို့
မရပါ။ ဒါကြောင့် token ကို Python level မှာ အစားထိုးပြီး bot ကို run
ပေးတဲ့ loader script (`run_patched_bot.py`) ကို ဖန်တီးပေးပါတယ်။
keyflow overlay (keyflow_bot.py) မသုံးဘဲ bot တိုက်ရိုက် run လိုရင် သုံးပါ။

    python3 patch_tool.py token "8960099014:AAGTdr-..."

ရလဒ်: run_patched_bot.py (တွဲလျက် ဖန်တီး) → `python3 run_patched_bot.py`

═════════════════════════════════════════════════════════════
TELEGRAM USERNAME (banner ပြင်းဆင် loader ဖန်တီးခြင်း)
═════════════════════════════════════════════════════════════
Binary ထဲက @KENOBEE username က compress လုပ်ထားတာမို့ binary patch လုပ်လို့
မရပါ။ ဒါကြောင့် import အချိန် print ထွက်တဲ့ banner/credit စာသားတွေကို
ဖမ်းယူပြီး username ကို အစားထိုး ပုံနှိပ်ပေးတဲ့ loader ကို ဖန်တီးပေးပါတယ်။

    python3 patch_tool.py name YOURNAME

ရလဒ်: run_patched_bot.py (တွဲလျက် ဖန်တီး) → `python3 run_patched_bot.py`

* token loader နဲ့ name loader နှစ်ခုလုံး run_patched_bot.py နာမည်နဲ့ ဖန်တီးတာမို့
  တစ်ခုထဲကိုပဲ သုံးချင်ရင် အခြားတစ်ခုကို ဖျက်ပါ။
* နှစ်ခုလုံး လိုချင်ရင် run_patched_bot.py ထဲက code တွေကို ပေါင်းစပ်ပါ
  (token override ကို name loader ထဲမှာလည်း ထည့်လို့ရပါတယ်)။

═════════════════════════════════════════════════════════════
"""

import os
import struct
import sys

# ---------- constants (verified from full disassembly) -----------------------
PATCH_OFFSET = 0x9b32          # file offset of the 8-byte little-endian ID
PATCH_SIZE = 8                 # 8 bytes = one x86-64 immediate operand
ORIGINAL_ID = 8556036826       # hardcoded default in the .so
EXPECTED_PREFIX = bytes([0x49, 0xbc])   # 'movabs %r12, imm64' opcode

SO_NAME = 'sirzipp.cpython-311-x86_64-linux-gnu.so'


def current_id(data):
    return struct.unpack_from('<Q', data, PATCH_OFFSET)[0]


# ═════════════════════ ADMIN ID patch ══════════════════════
def patch_admin(path, new_id):
    with open(path, 'rb') as f:
        data = f.read()
    if len(data) < PATCH_OFFSET + PATCH_SIZE:
        sys.exit(f'[!] File is too small ({len(data)} bytes)')
    cur = current_id(data)
    prefix = data[PATCH_OFFSET - 2: PATCH_OFFSET]
    print(f'[*] Current ID in binary : {cur}')
    print(f'[?] Target file          : {path}')
    print(f'[?] Patch offset         : 0x{PATCH_OFFSET:x}')

    if prefix != EXPECTED_PREFIX:
        sys.exit(f'[!] Unexpected prefix bytes (0x{prefix.hex()}) — '
                 'binary version differs. This tool cannot patch it.')

    if not (0 <= new_id <= 0x7fffffffffffffff):
        sys.exit(f'[!] ID must be a positive integer (got {new_id})')
    if cur == new_id:
        print(f'[+] ID is already {new_id} — no change needed')
        return
    if cur != ORIGINAL_ID:
        print(f'[!] Binary holds an unusual ID ({cur}). Patching anyway — '
              'press Ctrl+C within 2s to abort')
        try:
            import time
            time.sleep(2)
        except KeyboardInterrupt:
            print('\n[~] Aborted.')
            return

    old_bytes = data[PATCH_OFFSET: PATCH_OFFSET + PATCH_SIZE]
    new_bytes = struct.pack('<Q', new_id)
    data = data[:PATCH_OFFSET] + new_bytes + data[PATCH_OFFSET + PATCH_SIZE:]

    backup = path + '.orig'
    if not os.path.exists(backup):
        with open(backup, 'wb') as f:
            f.write(open(path, 'rb').read())
        print(f'[*] Backup saved         : {backup}')

    with open(path, 'wb') as f:
        f.write(data)
    print(f'[+] Patched bytes        : {old_bytes.hex()} -> {new_bytes.hex()}')
    print(f'[+] New admin ID         : {new_id}')
    print('[✓] Done. Restart the bot for the change to take effect')


# ═════════════════════ BOT TOKEN loader ════════════════════
LOADER_TEMPLATE = '''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Auto-generated by patch_tool.py — bot token override loader.
# Binary ထဲက BOT_TOKEN ကို ဒီ token နဲ့ အစားထိုးပြီး bot ကို run ပေးတယ်။
import os
import sys

# binary မ import မလုပ်ခင် token ကို override ထားပါ
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# 1. Binary's own polling ကို block (import အချိန် bot အလိုအလျောက မစဘို့)
import telegram.ext as _ext
_ORIG_POLLING = _ext.Application.run_polling
_ext.Application.run_polling = lambda self, *a, **kw: None

import sirzipp

# 2. Token အစားထိုး
sirzipp.BOT_TOKEN = {token_repr!r}
print('[PATCH_TOOL] BOT_TOKEN overridden ->', sirzipp.BOT_TOKEN[:20] + '...')

# 3. Bot ကို ပုံမှန်အတိုင်း run (binary ထဲက handlers အကုန်လုံး အလုပ်လုပ်တယ်)
from telegram import BotCommand
from telegram.ext import (Application, CommandHandler, CallbackQueryHandler,
                          MessageHandler, filters)

# binary ထဲက bot ကို ဖွင့်ဖို့ run_polling ကို ပြန်ထား
_ext.Application.run_polling = _ORIG_POLLING

app = Application.builder().token(sirzipp.BOT_TOKEN).build()

# binary ထဲက handler commands ကို လိုအပ်ရင် ထပ်ထည့်ပါ
app.add_handler(CommandHandler('start', sirzipp.start))
app.add_handler(CommandHandler('addproxies', sirzipp.add_proxies_cmd))
app.add_handler(CallbackQueryHandler(sirzipp.handle_callbacks))
app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND,
                               sirzipp.handle_text))

# run_polling() သည် blocking method (PTB 22 — None ပြန်) — asyncio.run နဲ့
# မထုတ်ပါနဲ့၊ တိုက်ရိုက် call လုပ်လိုက်ရင် process က polling လုပ်နေမယ်
app.run_polling(allowed_updates=['message', 'callback_query'],
                drop_pending_updates=True)
'''


NAME_LOADER_TEMPLATE = '''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Auto-generated by patch_tool.py — Telegram username override loader.
# Binary ထဲက banner/credit text ထဲက "@KENOBEE" ကို \'{new_name}\' နဲ့
# အစားထိုးပြီး bot ကို run ပေးတယ်။
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# ── 1. import အချိန် banner ပုံနှိပ်ထွက်တာကို ဖမ်းယူ (capture) ──
import io
_buf = io.StringIO()
_old_stdout = sys.stdout
sys.stdout = _buf

# binary မ import မလုပ်ခင် binary ရဲ့ polling ကို block ထား (bot ကို ကိုယ်ထဲ run မှ)
import telegram.ext as _ext
_ORIG_POLLING = _ext.Application.run_polling
_ext.Application.run_polling = lambda self, *a, **kw: None

import sirzipp

sys.stdout = _old_stdout
_captured = _buf.getvalue()

# ── 2. KENOBEE အားလုံးကို ပြင်းထားတဲ့ နာမည်နဲ့ အစားထိုးပြီး ပုံနှိပ် ──
import re
_mod = _captured.replace('KENOBEE', {new_name!r})
print(_mod, end='')
print('[NAME_PATCH] Username overridden -> @%s' % {new_name!r})

# ── 3. Bot ကို ပုံမှန်အတိုင်း run ──
from telegram import BotCommand
from telegram.ext import (Application, CommandHandler, CallbackQueryHandler,
                          MessageHandler, filters)

_ext.Application.run_polling = _ORIG_POLLING

app = Application.builder().token(sirzipp.BOT_TOKEN).build()
app.add_handler(CommandHandler('start', sirzipp.start))
app.add_handler(CommandHandler('addproxies', sirzipp.add_proxies_cmd))
app.add_handler(CallbackQueryHandler(sirzipp.handle_callbacks))
app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND,
                               sirzipp.handle_text))

# run_polling() သည် blocking method (PTB 22 — None ပြန်) — asyncio.run နဲ့
# မထုတ်ပါနဲ့၊ တိုက်ရိုက် call လုပ်လိုက်ရင် process က polling လုပ်နေမယ်
app.run_polling(allowed_updates=['message', 'callback_query'],
                drop_pending_updates=True)
'''


def make_name_loader(new_name):
    out = os.path.join(os.getcwd(), 'run_patched_bot.py')
    with open(out, 'w', encoding='utf-8') as f:
        f.write(NAME_LOADER_TEMPLATE.format(new_name=new_name))
    try:
        os.chmod(out, 0o755)
    except OSError:
        pass
    print('[+] Name loader created:', out)
    print(f'[+] Username in banner/credit -> @{new_name}')
    print('[✓] Run it with: python3 run_patched_bot.py')


def make_token_loader(token):
    out = os.path.join(os.getcwd(), 'run_patched_bot.py')
    with open(out, 'w', encoding='utf-8') as f:
        f.write(LOADER_TEMPLATE.format(token_repr=token))
    try:
        os.chmod(out, 0o755)
    except OSError:
        pass
    print('[+] Loader created:', out)
    print('[✓] Run it with: python3 run_patched_bot.py')
    print('[!] Admin ID ကို ပြောင်းချင်ရင် patch_tool.py admin <ID> ကို')
    print('    အရင် run ပြီးမှ run_patched_bot.py ကို သုံးပါ')


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        sys.exit(0)

    mode = args[0]
    rest = args[1:]

    if mode == 'admin':
        restore = '--restore' in rest
        check = '--check-only' in rest
        new_id = None
        path_arg = None
        i = 0
        while i < len(rest):
            a = rest[i]
            if a == '--file' and i + 1 < len(rest):
                path_arg = rest[i + 1]
                i += 2
                continue
            if a in ('--restore', '--check-only'):
                i += 1
                continue
            if not a.startswith('-'):
                try:
                    new_id = int(a)
                except ValueError:
                    sys.exit(f'[!] Not a valid ID: {a}')
            i += 1
        path = path_arg or os.path.join(os.getcwd(), SO_NAME)
        if not os.path.exists(path):
            sys.exit(f'[!] File not found: {path}')
        if check:
            print('Current admin ID:', current_id(open(path, 'rb').read()),
                  f'({path})')
            return
        print(f'[?] File to patch        : {path}')
        if restore:
            new_id = ORIGINAL_ID
            print(f'[*] Restoring original ID {ORIGINAL_ID}')
        if new_id is None:
            sys.exit('[!] Missing target ID. Usage: patch_tool.py admin NEW_ID')
        patch_admin(path, new_id)

    elif mode == 'token':
        if not rest or rest[0].startswith('-'):
            sys.exit('[!] Missing token. Usage: patch_tool.py token "TOKEN"')
        token = rest[0]
        if not (token.count(':') == 1 and token.split(':')[0].isdigit()
                and len(token) > 30):
            print('[!] Token format looks unusual but proceeding anyway — '
                  'Telegram bot tokens are like 8960099014:AAGTdr-... '
                  '(30-50 chars, one colon)')
        make_token_loader(token)

    elif mode == 'name':
        # banner/name override loader — Telegram username ကို ပြောင်းပေးတဲ့ loader
        if not rest or rest[0].startswith('-'):
            sys.exit('[!] Missing name. Usage: patch_tool.py name NEW_NAME')
        new_name = rest[0]
        make_name_loader(new_name)

    elif mode == 'check':
        path = rest[0] if rest else os.path.join(
            os.path.dirname(os.path.abspath(__file__)), SO_NAME)
        data = open(path, 'rb').read()
        print('Admin ID:', current_id(data))

    else:
        sys.exit(f'[!] Unknown mode: {mode!r}. '
                 'Use "admin", "token" or "name".\n{__doc__}')


if __name__ == '__main__':
    main()
